export type RiskBand = 'green' | 'amber' | 'red'

export type CovenantStatus = 'GREEN' | 'AMBER' | 'BREACHED'
export type RepaymentStatus = 'CURRENT' | 'SMA_0' | 'SMA_1' | 'NPA'
export type QPRStatus = 'ON_TIME' | 'LATE' | 'MISSED'

export interface LendProject {
  id: string
  name: string
  developer: string
  developer_id: string
  city: string
  exposure_cr: number
  outstanding_cr: number
  risk_band: RiskBand
  risk_score: number
  flagged_quarter: string | null
  recovery_window: string | null
  rera_id: string
  loan_sanctioned: string
  loan_type: 'Construction Finance' | 'Term Loan' | 'LAP'
  // Detailed loan layer — populated for RED / AMBER; optional for GREEN
  sanctioned_cr?: number
  drawn_pct?: number
  built_pct?: number
  next_tranche_cr?: number
  undisbursed_cr?: number
  escrow_pct?: number
  construction_pct?: number
  covenant_status?: CovenantStatus
  repayment_status?: RepaymentStatus
  last_qpr_status?: QPRStatus
  qpr_consecutive_misses?: number
  early_warning_signals?: string[]
  stress_note?: string
}

export interface DeveloperFactor {
  name: string
  impact: number  // positive = good, negative = bad (-100 to +100)
  detail: string
}

export interface DeveloperProfile {
  id: string
  name: string
  score: number
  band: RiskBand
  headquarter: string
  years_active: number
  total_projects: number
  active_loans: number
  factors: DeveloperFactor[]
  score_trend: Array<{ quarter: string; score: number }>
}

export const LEND_PROJECTS: LendProject[] = [
  // ── RED (3) ────────────────────────────────────────────────────
  {
    id: 'ozone-urbana',
    name: 'Ozone Urbana',
    developer: 'Ozone Group',
    developer_id: 'ozone-group',
    city: 'Bengaluru',
    exposure_cr: 250,
    outstanding_cr: 180,
    risk_band: 'red',
    risk_score: 312,
    flagged_quarter: 'Q3 2021',
    recovery_window: 'RECOVERABLE',
    rera_id: 'PRM/KA/RERA/1251/309/PR/171016/000112',
    loan_sanctioned: 'Mar 2019',
    loan_type: 'Construction Finance',
    sanctioned_cr: 250,
    drawn_pct: 72,
    built_pct: 43,
    next_tranche_cr: 40,
    undisbursed_cr: 70,
    escrow_pct: 8,
    construction_pct: 43,
    covenant_status: 'BREACHED',
    repayment_status: 'SMA_1',
    last_qpr_status: 'MISSED',
    qpr_consecutive_misses: 8,
    early_warning_signals: [
      'QPR non-filing 8 consecutive quarters',
      'Escrow balance 8% vs 70% RERA minimum',
      'Drawn-vs-built gap: 29 percentage points',
      'ED FEMA attachment ₹423 Cr on developer assets',
      'HC stay on all refund orders',
    ],
    stress_note: 'Covenant breach on escrow maintenance ratio (RERA 70% minimum). EMI SMA-1 as of Q1 2024. Recommend formal notice and cross-collateral demand.',
  },
  {
    id: 'concord-meridian',
    name: 'Concord Meridian',
    developer: 'Concord Buildcon',
    developer_id: 'concord-buildcon',
    city: 'Bengaluru',
    exposure_cr: 140,
    outstanding_cr: 140,
    risk_band: 'red',
    risk_score: 285,
    flagged_quarter: 'Q2 2022',
    recovery_window: 'AT RISK',
    rera_id: 'PRM/KA/RERA/1251/309/PR/181024/000241',
    loan_sanctioned: 'Oct 2020',
    loan_type: 'Construction Finance',
    sanctioned_cr: 140,
    drawn_pct: 100,
    built_pct: 52,
    next_tranche_cr: 0,
    undisbursed_cr: 0,
    escrow_pct: 6,
    construction_pct: 52,
    covenant_status: 'BREACHED',
    repayment_status: 'NPA',
    last_qpr_status: 'MISSED',
    qpr_consecutive_misses: 5,
    early_warning_signals: [
      'Fully drawn — no undisbursed capital as leverage',
      'Escrow 6% — worst in amber/red portfolio',
      'Construction halted Q3 2023 (worker dispute)',
      'Developer directors under Look-out Notice',
      'Pending NCLT filing by sub-contractor',
    ],
    stress_note: 'NPA classification likely Q2 2024 if no restructure. 100% drawn, construction stalled. Recovery window closed without court-ordered asset attachment.',
  },
  {
    id: 'regent-heights',
    name: 'Regent Heights',
    developer: 'Regent Estates',
    developer_id: 'regent-estates',
    city: 'Bengaluru',
    exposure_cr: 100,
    outstanding_cr: 100,
    risk_band: 'red',
    risk_score: 298,
    flagged_quarter: 'Q1 2022',
    recovery_window: 'AT RISK',
    rera_id: 'PRM/KA/RERA/1251/309/PR/200315/000318',
    loan_sanctioned: 'Jan 2021',
    loan_type: 'Term Loan',
    sanctioned_cr: 100,
    drawn_pct: 95,
    built_pct: 61,
    next_tranche_cr: 5,
    undisbursed_cr: 5,
    escrow_pct: 11,
    construction_pct: 61,
    covenant_status: 'BREACHED',
    repayment_status: 'SMA_0',
    last_qpr_status: 'LATE',
    qpr_consecutive_misses: 2,
    early_warning_signals: [
      '2 consecutive late QPR filings Q3–Q4 2023',
      'Escrow 11% — 59 pp below RERA minimum',
      'Drawn-vs-built gap: 34 percentage points',
      '3 consumer forum complaints filed Q4 2023',
      'Term loan covenant: minimum 25% escrow — BREACHED',
    ],
    stress_note: 'SMA-0 since Q4 2023. Remaining ₹5 Cr undisbursed on hold pending escrow remediation. 60-day cure period expires July 2024.',
  },

  // ── AMBER (9) ─────────────────────────────────────────────────
  {
    id: 'skylark-arcadia',
    name: 'Skylark Arcadia',
    developer: 'Skylark Mansions',
    developer_id: 'skylark-mansions',
    city: 'Bengaluru',
    exposure_cr: 65,
    outstanding_cr: 65,
    risk_band: 'amber',
    risk_score: 540,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/190211/000178',
    loan_sanctioned: 'Feb 2020',
    loan_type: 'Construction Finance',
    sanctioned_cr: 65,
    drawn_pct: 68,
    built_pct: 57,
    escrow_pct: 19,
    construction_pct: 57,
    covenant_status: 'AMBER',
    repayment_status: 'CURRENT',
    last_qpr_status: 'LATE',
    qpr_consecutive_misses: 0,
    early_warning_signals: [
      'QPR filing 11 days late Q3 2025',
      'Construction 11% behind schedule',
      'Escrow 19% — marginally above floor',
      'Sub-contractor dispute (₹3.2 Cr claim pending)',
    ],
  },
  {
    id: 'mantri-techzone',
    name: 'Mantri Techzone',
    developer: 'Mantri Developers',
    developer_id: 'mantri-developers',
    city: 'Bengaluru',
    exposure_cr: 88,
    outstanding_cr: 88,
    risk_band: 'amber',
    risk_score: 510,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/180822/000156',
    loan_sanctioned: 'Aug 2019',
    loan_type: 'Construction Finance',
    sanctioned_cr: 88,
    drawn_pct: 81,
    built_pct: 69,
    escrow_pct: 14,
    construction_pct: 69,
    covenant_status: 'AMBER',
    repayment_status: 'CURRENT',
    last_qpr_status: 'LATE',
    early_warning_signals: ['4 late QPR filings in 12 quarters', 'Escrow dipped to 14% — regulatory notice received', 'Contractor dispute Q2 2023 (₹6.2 Cr HC claim)'],
  },
  {
    id: 'confident-crystal',
    name: 'Confident Crystal',
    developer: 'Confident Group',
    developer_id: 'confident-group',
    city: 'Bengaluru',
    exposure_cr: 70,
    outstanding_cr: 70,
    risk_band: 'amber',
    risk_score: 555,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/200614/000332',
    loan_sanctioned: 'Jun 2021',
    loan_type: 'Term Loan',
    sanctioned_cr: 70,
    drawn_pct: 74,
    built_pct: 66,
    escrow_pct: 22,
    construction_pct: 66,
    covenant_status: 'AMBER',
    repayment_status: 'CURRENT',
    last_qpr_status: 'MISSED',
    qpr_consecutive_misses: 1,
    early_warning_signals: ['1 missed QPR Q3 2023 — show-cause notice received', 'Monsoon delay cited; K-RERA accepted extension'],
  },
  {
    id: 'shriram-suhaana',
    name: 'Shriram Suhaana',
    developer: 'Shriram Properties',
    developer_id: 'shriram-properties',
    city: 'Bengaluru',
    exposure_cr: 45,
    outstanding_cr: 45,
    risk_band: 'amber',
    risk_score: 532,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/210308/000389',
    loan_sanctioned: 'Mar 2022',
    loan_type: 'Construction Finance',
    sanctioned_cr: 45,
    drawn_pct: 62,
    built_pct: 54,
    escrow_pct: 24,
    construction_pct: 54,
    covenant_status: 'GREEN',
    repayment_status: 'CURRENT',
    last_qpr_status: 'ON_TIME',
    early_warning_signals: ['Sales velocity slowed — 18 units unsold (28% of inventory)', 'Minor delay in BBMP occupancy certificate application'],
  },
  {
    id: 'mana-palms',
    name: 'Mana Palms',
    developer: 'Mana Developers',
    developer_id: 'mana-developers',
    city: 'Bengaluru',
    exposure_cr: 38,
    outstanding_cr: 38,
    risk_band: 'amber',
    risk_score: 518,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/211119/000412',
    loan_sanctioned: 'Nov 2022',
    loan_type: 'LAP',
    sanctioned_cr: 38,
    drawn_pct: 100,
    built_pct: 78,
    escrow_pct: 16,
    construction_pct: 78,
    covenant_status: 'AMBER',
    repayment_status: 'CURRENT',
    last_qpr_status: 'LATE',
    early_warning_signals: ['LAP — collateral at risk if LAP-funded project stalls', 'Escrow 16% below RERA minimum for 2 quarters', '1 consumer complaint filed Q1 2024'],
  },
  {
    id: 'hubli-grand-central',
    name: 'Hubli Grand Central',
    developer: 'Hubli Constructions',
    developer_id: 'hubli-constructions',
    city: 'Hubli-Dharwad',
    exposure_cr: 32,
    outstanding_cr: 32,
    risk_band: 'amber',
    risk_score: 495,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/200921/000301',
    loan_sanctioned: 'Sep 2021',
    loan_type: 'Construction Finance',
    sanctioned_cr: 32,
    drawn_pct: 79,
    built_pct: 65,
    escrow_pct: 17,
    construction_pct: 65,
    covenant_status: 'AMBER',
    repayment_status: 'CURRENT',
    last_qpr_status: 'MISSED',
    qpr_consecutive_misses: 1,
    early_warning_signals: ['First QPR non-filing Q2 2023 — show-cause issued', 'Lowest risk score of AMBER book', 'Tier-2 city: resale liquidity limited in stress scenario'],
  },
  {
    id: 'mangalore-heights',
    name: 'Mangalore Heights',
    developer: 'KMP Builders',
    developer_id: 'kmp-builders',
    city: 'Mangaluru',
    exposure_cr: 41,
    outstanding_cr: 41,
    risk_band: 'amber',
    risk_score: 512,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/191205/000204',
    loan_sanctioned: 'Dec 2020',
    loan_type: 'Term Loan',
    sanctioned_cr: 41,
    drawn_pct: 88,
    built_pct: 72,
    escrow_pct: 21,
    construction_pct: 72,
    covenant_status: 'GREEN',
    repayment_status: 'CURRENT',
    last_qpr_status: 'ON_TIME',
    early_warning_signals: ['Coastal regulation zone clearance pending OC', 'Developer cash flow squeezed — sister project dispute'],
  },
  {
    id: 'bellary-emerald',
    name: 'Ballari Emerald',
    developer: 'Deccan Infra',
    developer_id: 'deccan-infra',
    city: 'Ballari',
    exposure_cr: 35,
    outstanding_cr: 35,
    risk_band: 'amber',
    risk_score: 488,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/220103/000445',
    loan_sanctioned: 'Jan 2023',
    loan_type: 'Construction Finance',
    sanctioned_cr: 35,
    drawn_pct: 71,
    built_pct: 55,
    escrow_pct: 13,
    construction_pct: 55,
    covenant_status: 'AMBER',
    repayment_status: 'SMA_0',
    last_qpr_status: 'LATE',
    qpr_consecutive_misses: 0,
    early_warning_signals: ['SMA-0 since Q4 2023 — 1 EMI 31 days late', 'Ballari market slowdown — absorption rate 58%', 'Escrow 13% for 3 consecutive quarters'],
    stress_note: 'SMA-0 classification. Ballari micro-market illiquidity compounds recovery risk. Recommend enhanced monitoring and site inspection within 30 days.',
  },

  // ── GREEN (28) ────────────────────────────────────────────────
  {
    id: 'divya-villas',
    name: 'Divya Villas',
    developer: 'Zion Builders',
    developer_id: 'zion-builders',
    city: 'Mysuru',
    exposure_cr: 42,
    outstanding_cr: 38,
    risk_band: 'green',
    risk_score: 780,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/170412/000034',
    loan_sanctioned: 'Apr 2018',
    loan_type: 'Construction Finance',
  },
  {
    id: 'prestige-lakeside',
    name: 'Prestige Lakeside',
    developer: 'Prestige Group',
    developer_id: 'prestige-group',
    city: 'Bengaluru',
    exposure_cr: 95,
    outstanding_cr: 82,
    risk_band: 'green',
    risk_score: 820,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/180614/000143',
    loan_sanctioned: 'Jun 2019',
    loan_type: 'Construction Finance',
  },
  {
    id: 'sobha-dream-acres',
    name: 'Sobha Altair',
    developer: 'Sobha Ltd',
    developer_id: 'sobha-ltd',
    city: 'Bengaluru Urban',
    exposure_cr: 85,
    outstanding_cr: 71,
    risk_band: 'green',
    risk_score: 810,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/446/PR/070126/008388',
    loan_sanctioned: 'Sep 2019',
    loan_type: 'Construction Finance',
  },
  {
    id: 'brigade-residences',
    name: 'Brigade Lumina',
    developer: 'Brigade Group',
    developer_id: 'brigade-group',
    city: 'Bengaluru Urban',
    exposure_cr: 72,
    outstanding_cr: 60,
    risk_band: 'green',
    risk_score: 795,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/230326/008545',
    loan_sanctioned: 'Jan 2020',
    loan_type: 'Term Loan',
  },
  {
    id: 'godrej-splendour',
    name: 'Godrej Parkshire',
    developer: 'Godrej Properties',
    developer_id: 'godrej-properties',
    city: 'Bengaluru Rural',
    exposure_cr: 68,
    outstanding_cr: 55,
    risk_band: 'green',
    risk_score: 760,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1250/304/PR/090126/008393',
    loan_sanctioned: 'Mar 2020',
    loan_type: 'Construction Finance',
  },
  {
    id: 'puravankara-east',
    name: 'Purva East End',
    developer: 'Puravankara',
    developer_id: 'puravankara',
    city: 'Bengaluru',
    exposure_cr: 55,
    outstanding_cr: 44,
    risk_band: 'green',
    risk_score: 745,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/191104/000211',
    loan_sanctioned: 'Nov 2020',
    loan_type: 'Construction Finance',
  },
  {
    id: 'total-env-retreat',
    name: 'Total Env. Retreat',
    developer: 'Total Environment',
    developer_id: 'total-environment',
    city: 'Bengaluru',
    exposure_cr: 62,
    outstanding_cr: 50,
    risk_band: 'green',
    risk_score: 772,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/200205/000275',
    loan_sanctioned: 'Feb 2021',
    loan_type: 'Term Loan',
  },
  {
    id: 'embassy-edge',
    name: 'Embassy Verde Phase 2',
    developer: 'Embassy Group',
    developer_id: 'embassy-group',
    city: 'Bengaluru Rural',
    exposure_cr: 48,
    outstanding_cr: 38,
    risk_band: 'green',
    risk_score: 785,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1250/303/PR/201125/008263',
    loan_sanctioned: 'Apr 2021',
    loan_type: 'Construction Finance',
  },
  {
    id: 'assetz-earth',
    name: 'Assetz Muse & Maison',
    developer: 'Assetz Property',
    developer_id: 'assetz-property',
    city: 'Bengaluru Urban',
    exposure_cr: 78,
    outstanding_cr: 64,
    risk_band: 'green',
    risk_score: 768,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/310/PR/040526/008618',
    loan_sanctioned: 'Jul 2021',
    loan_type: 'Construction Finance',
  },
  {
    id: 'prestige-primrose',
    name: 'Prestige Greenbrook',
    developer: 'Prestige Group',
    developer_id: 'prestige-group',
    city: 'Bengaluru Rural',
    exposure_cr: 67,
    outstanding_cr: 55,
    risk_band: 'green',
    risk_score: 802,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1250/303/PR/260925/008123',
    loan_sanctioned: 'Oct 2021',
    loan_type: 'Construction Finance',
  },
  {
    id: 'nandi-hills-retreat',
    name: 'Nandi Hills Retreat',
    developer: 'Nandi Developers',
    developer_id: 'nandi-developers',
    city: 'Bengaluru Rural',
    exposure_cr: 38,
    outstanding_cr: 28,
    risk_band: 'green',
    risk_score: 730,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/201201/000362',
    loan_sanctioned: 'Dec 2021',
    loan_type: 'LAP',
  },
  {
    id: 'vaishnavi-terraces',
    name: 'Vaishnavi Terraces',
    developer: 'Vaishnavi Group',
    developer_id: 'vaishnavi-group',
    city: 'Bengaluru',
    exposure_cr: 52,
    outstanding_cr: 40,
    risk_band: 'green',
    risk_score: 755,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/210220/000378',
    loan_sanctioned: 'Feb 2022',
    loan_type: 'Construction Finance',
  },
  {
    id: 'nitesh-napa',
    name: 'Nitesh Napa Valley',
    developer: 'Nitesh Estates',
    developer_id: 'nitesh-estates',
    city: 'Bengaluru',
    exposure_cr: 35,
    outstanding_cr: 26,
    risk_band: 'green',
    risk_score: 718,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/210405/000391',
    loan_sanctioned: 'Apr 2022',
    loan_type: 'Term Loan',
  },
  {
    id: 'adarsh-palm',
    name: 'Adarsh Palm Retreat',
    developer: 'Adarsh Developers',
    developer_id: 'adarsh-developers',
    city: 'Bengaluru',
    exposure_cr: 60,
    outstanding_cr: 48,
    risk_band: 'green',
    risk_score: 764,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/210614/000408',
    loan_sanctioned: 'Jun 2022',
    loan_type: 'Construction Finance',
  },
  {
    id: 'mahindra-windchimes',
    name: 'Mahindra Blossom',
    developer: 'Mahindra Lifespace',
    developer_id: 'mahindra-lifespace',
    city: 'Bengaluru Urban',
    exposure_cr: 44,
    outstanding_cr: 33,
    risk_band: 'green',
    risk_score: 748,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/446/PR/171225/008348',
    loan_sanctioned: 'Aug 2022',
    loan_type: 'Construction Finance',
  },
  {
    id: 'salarpuria-gold',
    name: 'Salarpuria Gold Summit',
    developer: 'Salarpuria Sattva',
    developer_id: 'salarpuria-sattva',
    city: 'Bengaluru',
    exposure_cr: 58,
    outstanding_cr: 46,
    risk_band: 'green',
    risk_score: 790,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/211005/000436',
    loan_sanctioned: 'Oct 2022',
    loan_type: 'Construction Finance',
  },
  {
    id: 'concorde-neopolis',
    name: 'Concorde Neopolis',
    developer: 'Concorde Group',
    developer_id: 'concorde-group',
    city: 'Bengaluru',
    exposure_cr: 39,
    outstanding_cr: 29,
    risk_band: 'green',
    risk_score: 728,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/211215/000452',
    loan_sanctioned: 'Dec 2022',
    loan_type: 'Term Loan',
  },
  {
    id: 'sumadhura-panorama',
    name: 'Sumadhura Panorama',
    developer: 'Sumadhura',
    developer_id: 'sumadhura',
    city: 'Bengaluru',
    exposure_cr: 46,
    outstanding_cr: 36,
    risk_band: 'green',
    risk_score: 742,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/220210/000468',
    loan_sanctioned: 'Feb 2023',
    loan_type: 'Construction Finance',
  },
  {
    id: 'vijaya-heritage',
    name: 'Vijaya Heritage',
    developer: 'Vijaya Builders',
    developer_id: 'vijaya-builders',
    city: 'Mysuru',
    exposure_cr: 28,
    outstanding_cr: 20,
    risk_band: 'green',
    risk_score: 712,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/220415/000487',
    loan_sanctioned: 'Apr 2023',
    loan_type: 'LAP',
  },
  {
    id: 'rohan-dhruva',
    name: 'Rohan Dhruva',
    developer: 'Rohan Group',
    developer_id: 'rohan-group',
    city: 'Bengaluru',
    exposure_cr: 54,
    outstanding_cr: 42,
    risk_band: 'green',
    risk_score: 758,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/220620/000502',
    loan_sanctioned: 'Jun 2023',
    loan_type: 'Construction Finance',
  },
  {
    id: 'casagrand-firstcity',
    name: 'Casagrand FirstCity',
    developer: 'Casagrand',
    developer_id: 'casagrand',
    city: 'Bengaluru',
    exposure_cr: 49,
    outstanding_cr: 38,
    risk_band: 'green',
    risk_score: 736,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/220908/000521',
    loan_sanctioned: 'Sep 2023',
    loan_type: 'Construction Finance',
  },
  {
    id: 'brigade-cornerstone',
    name: 'Brigade Belvedere',
    developer: 'Brigade Group',
    developer_id: 'brigade-group',
    city: 'Bengaluru Urban',
    exposure_cr: 76,
    outstanding_cr: 62,
    risk_band: 'green',
    risk_score: 799,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/446/PR/240326/008549',
    loan_sanctioned: 'Nov 2023',
    loan_type: 'Term Loan',
  },
  {
    id: 'divyasree-77',
    name: 'DivyaSree 77 Place',
    developer: 'DivyaSree Developers',
    developer_id: 'divyasree-developers',
    city: 'Bengaluru',
    exposure_cr: 63,
    outstanding_cr: 50,
    risk_band: 'green',
    risk_score: 773,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/230118/000555',
    loan_sanctioned: 'Jan 2024',
    loan_type: 'Construction Finance',
  },
  {
    id: 'prestige-finsbury',
    name: 'Prestige Raintree Park',
    developer: 'Prestige Group',
    developer_id: 'prestige-group',
    city: 'Bengaluru Urban',
    exposure_cr: 88,
    outstanding_cr: 74,
    risk_band: 'green',
    risk_score: 815,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/446/PR/270824/006981',
    loan_sanctioned: 'Mar 2024',
    loan_type: 'Construction Finance',
  },
  {
    id: 'sobha-city',
    name: 'One Residences at Sobha One World',
    developer: 'Sobha Ltd',
    developer_id: 'sobha-ltd',
    city: 'Bengaluru Rural',
    exposure_cr: 74,
    outstanding_cr: 61,
    risk_band: 'green',
    risk_score: 806,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1250/304/PR/080526/008634',
    loan_sanctioned: 'May 2024',
    loan_type: 'Construction Finance',
  },
  {
    id: 'purva-gainz',
    name: 'Purva Gainz',
    developer: 'Puravankara',
    developer_id: 'puravankara',
    city: 'Bengaluru',
    exposure_cr: 40,
    outstanding_cr: 30,
    risk_band: 'green',
    risk_score: 722,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/230712/000604',
    loan_sanctioned: 'Jul 2024',
    loan_type: 'LAP',
  },
  {
    id: 'kaveri-residency',
    name: 'Kaveri Residency',
    developer: 'NCR Builders',
    developer_id: 'ncr-builders',
    city: 'Raichur',
    exposure_cr: 22,
    outstanding_cr: 15,
    risk_band: 'green',
    risk_score: 699,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/230918/000621',
    loan_sanctioned: 'Sep 2024',
    loan_type: 'Construction Finance',
  },
  {
    id: 'sterling-oaks',
    name: 'Sterling Oaks',
    developer: 'Sterling Developers',
    developer_id: 'sterling-developers',
    city: 'Mysuru',
    exposure_cr: 33,
    outstanding_cr: 24,
    risk_band: 'green',
    risk_score: 710,
    flagged_quarter: null,
    recovery_window: null,
    rera_id: 'PRM/KA/RERA/1251/309/PR/231105/000638',
    loan_sanctioned: 'Nov 2024',
    loan_type: 'Construction Finance',
  },
]

// ── Developer profiles for Screen 4 ────────────────────────────────
export const LEND_DEVELOPERS: Record<string, DeveloperProfile> = {
  'ozone-group': {
    id: 'ozone-group',
    name: 'Ozone Group',
    score: 312,
    band: 'red',
    headquarter: 'Bengaluru',
    years_active: 18,
    total_projects: 14,
    active_loans: 3,
    factors: [
      { name: 'QPR Compliance History',  impact: -42, detail: '8 consecutive quarters of QPR default — statutory maximum breach' },
      { name: 'Active Litigation',        impact: -28, detail: '3 High Court cases, 2 criminal complaints, NCLT filing' },
      { name: 'Escrow Discipline',        impact: -18, detail: 'Escrow balance <8% of collected amount — severe violation' },
      { name: 'Construction Progress',    impact: -14, detail: 'Physical progress 22% behind schedule at last RERA inspection' },
      { name: 'Past Project Delivery',    impact:  +6, detail: '2 of 7 completed projects delivered within 12 months of deadline' },
      { name: 'Financial Transparency',   impact: -12, detail: 'Repeated failures to file audited project accounts' },
    ],
    score_trend: [
      { quarter: 'Q3 2022', score: 580 },
      { quarter: 'Q4 2022', score: 510 },
      { quarter: 'Q1 2023', score: 430 },
      { quarter: 'Q2 2023', score: 360 },
      { quarter: 'Q3 2023', score: 320 },
      { quarter: 'Q4 2023', score: 285 },
      { quarter: 'Q1 2024', score: 312 },
    ],
  },
  'prestige-group': {
    id: 'prestige-group',
    name: 'Prestige Group',
    score: 840,
    band: 'green',
    headquarter: 'Bengaluru',
    years_active: 40,
    total_projects: 81,
    active_loans: 3,
    factors: [
      { name: 'QPR Compliance History',  impact: +38, detail: '96% on-time QPR submissions across all active projects' },
      { name: 'Active Litigation',        impact: +22, detail: 'Zero active litigations on funded projects; minimal historical cases' },
      { name: 'Escrow Discipline',        impact: +18, detail: 'Escrow maintained at 32–45% — well above RERA minimum' },
      { name: 'Construction Progress',    impact: +15, detail: 'Physical progress ahead of schedule on 2 of 3 Kaveri HFC projects' },
      { name: 'Past Project Delivery',    impact: +20, detail: '89% of completed projects delivered within RERA deadline' },
      { name: 'Financial Transparency',   impact: +12, detail: 'Audited accounts filed consistently; no outstanding penalties' },
    ],
    score_trend: [
      { quarter: 'Q3 2022', score: 818 },
      { quarter: 'Q4 2022', score: 825 },
      { quarter: 'Q1 2023', score: 832 },
      { quarter: 'Q2 2023', score: 835 },
      { quarter: 'Q3 2023', score: 840 },
      { quarter: 'Q4 2023', score: 838 },
      { quarter: 'Q1 2024', score: 840 },
    ],
  },
  'brigade-group': {
    id: 'brigade-group',
    name: 'Brigade Group',
    score: 810,
    band: 'green',
    headquarter: 'Bengaluru',
    years_active: 38,
    total_projects: 59,
    active_loans: 2,
    factors: [
      { name: 'QPR Compliance History',  impact: +35, detail: '94% on-time submissions; 2 late filings resolved within cure period' },
      { name: 'Active Litigation',        impact: +18, detail: 'One minor consumer forum dispute — no financial exposure' },
      { name: 'Escrow Discipline',        impact: +20, detail: 'Escrow maintained above 28%; withdrawals aligned with milestones' },
      { name: 'Construction Progress',    impact: +14, detail: 'On-track or ahead across both Kaveri HFC-funded projects' },
      { name: 'Past Project Delivery',    impact: +18, detail: '85% on-time delivery track record across 38 years' },
      { name: 'Financial Transparency',   impact: +10, detail: 'Clean audit history; no RERA-imposed penalties' },
    ],
    score_trend: [
      { quarter: 'Q3 2022', score: 792 },
      { quarter: 'Q4 2022', score: 798 },
      { quarter: 'Q1 2023', score: 802 },
      { quarter: 'Q2 2023', score: 805 },
      { quarter: 'Q3 2023', score: 808 },
      { quarter: 'Q4 2023', score: 812 },
      { quarter: 'Q1 2024', score: 810 },
    ],
  },
  'skylark-mansions': {
    id: 'skylark-mansions',
    name: 'Skylark Mansions',
    score: 540,
    band: 'amber',
    headquarter: 'Bengaluru',
    years_active: 22,
    total_projects: 19,
    active_loans: 1,
    factors: [
      { name: 'QPR Compliance History',  impact: -12, detail: '3 late QPR filings in last 8 quarters — escalating trend' },
      { name: 'Active Litigation',        impact: -8,  detail: '2 consumer forum cases, ₹18 L total claimed; outcome uncertain' },
      { name: 'Escrow Discipline',        impact: +8,  detail: 'Escrow at 19% — marginally above RERA minimum threshold' },
      { name: 'Construction Progress',    impact: -6,  detail: 'Physical progress 11% behind last QPR milestone' },
      { name: 'Past Project Delivery',    impact: +4,  detail: '70% of past projects delivered within 18-month extension window' },
      { name: 'Financial Transparency',   impact: -5,  detail: 'Minor disclosure gaps in Q3 2023 audit; resolved post-inquiry' },
    ],
    score_trend: [
      { quarter: 'Q3 2022', score: 610 },
      { quarter: 'Q4 2022', score: 590 },
      { quarter: 'Q1 2023', score: 575 },
      { quarter: 'Q2 2023', score: 560 },
      { quarter: 'Q3 2023', score: 548 },
      { quarter: 'Q4 2023', score: 542 },
      { quarter: 'Q1 2024', score: 540 },
    ],
  },
  'sobha-ltd': {
    id: 'sobha-ltd',
    name: 'Sobha Ltd',
    score: 820,
    band: 'green',
    headquarter: 'Bengaluru',
    years_active: 30,
    total_projects: 122,
    active_loans: 2,
    factors: [
      { name: 'QPR Compliance History',  impact: +36, detail: '98% on-time QPR filings; recognised by K-RERA for compliance' },
      { name: 'Active Litigation',        impact: +20, detail: 'No active litigations on Kaveri HFC-funded projects' },
      { name: 'Escrow Discipline',        impact: +18, detail: 'Escrow consistently above 35%; withdrawals quarterly with milestone proof' },
      { name: 'Construction Progress',    impact: +16, detail: 'In-house construction model — predictable progress with zero sub-contractor risk' },
      { name: 'Past Project Delivery',    impact: +22, detail: '91% on-time delivery; industry benchmark for Bengaluru residential' },
      { name: 'Financial Transparency',   impact: +14, detail: 'NSE/BSE listed; quarterly results and RERA disclosures fully aligned' },
    ],
    score_trend: [
      { quarter: 'Q3 2022', score: 808 },
      { quarter: 'Q4 2022', score: 812 },
      { quarter: 'Q1 2023', score: 815 },
      { quarter: 'Q2 2023', score: 818 },
      { quarter: 'Q3 2023', score: 820 },
      { quarter: 'Q4 2023', score: 822 },
      { quarter: 'Q1 2024', score: 820 },
    ],
  },
  'mantri-developers': {
    id: 'mantri-developers',
    name: 'Mantri Developers',
    score: 510,
    band: 'amber',
    headquarter: 'Bengaluru',
    years_active: 28,
    total_projects: 24,
    active_loans: 1,
    factors: [
      { name: 'QPR Compliance History',  impact: -15, detail: '4 late QPR filings and 1 missed filing in past 12 quarters' },
      { name: 'Active Litigation',        impact: -10, detail: '1 High Court case (homebuyer class action), ₹6.2 Cr at risk' },
      { name: 'Escrow Discipline',        impact: -8,  detail: 'Escrow dipped to 14% for 2 quarters — regulatory notice received' },
      { name: 'Construction Progress',    impact: -5,  detail: 'Construction 14% behind schedule; contractor dispute Q2 2023' },
      { name: 'Past Project Delivery',    impact: +6,  detail: '65% on-time delivery rate; improving trend on recent projects' },
      { name: 'Financial Transparency',   impact: -3,  detail: 'Audited statement for FY 2022–23 filed 74 days late' },
    ],
    score_trend: [
      { quarter: 'Q3 2022', score: 590 },
      { quarter: 'Q4 2022', score: 572 },
      { quarter: 'Q1 2023', score: 552 },
      { quarter: 'Q2 2023', score: 535 },
      { quarter: 'Q3 2023', score: 524 },
      { quarter: 'Q4 2023', score: 515 },
      { quarter: 'Q1 2024', score: 510 },
    ],
  },
}

// Convenience: list of all project IDs (for generateStaticParams)
export const LEND_PROJECT_IDS = LEND_PROJECTS.map(p => p.id)

// Convenience: list of developer IDs (for generateStaticParams)
export const LEND_DEVELOPER_IDS = Object.keys(LEND_DEVELOPERS)

// Band styling helpers
export const BAND_COLOR = {
  red:   { text: '#E74C3C', bg: 'rgba(231,76,60,0.10)', border: 'rgba(231,76,60,0.28)' },
  amber: { text: '#F39C12', bg: 'rgba(243,156,18,0.10)', border: 'rgba(243,156,18,0.28)' },
  green: { text: '#2ECC71', bg: 'rgba(46,204,113,0.10)', border: 'rgba(46,204,113,0.28)' },
}

export const BAND_LABEL = { red: 'HIGH RISK', amber: 'WATCH', green: 'HEALTHY' }

// ── Ozone Urbana anchor data ─────────────────────────────────────────────────

export interface TrancheRow {
  id: string
  amount_cr: number
  date: string
  status: 'DISBURSED' | 'PENDING' | 'CONDITIONAL'
  milestone: string
  milestone_met: boolean
}

export const OZONE_TRANCHES: TrancheRow[] = [
  { id: 'T1', amount_cr: 50, date: 'Jan 2021', status: 'DISBURSED',    milestone: 'Foundation complete',       milestone_met: true  },
  { id: 'T2', amount_cr: 40, date: 'Apr 2021', status: 'DISBURSED',    milestone: 'Plinth level complete',     milestone_met: true  },
  { id: 'T3', amount_cr: 35, date: 'Jul 2021', status: 'DISBURSED',    milestone: 'Ground floor slab cast',    milestone_met: true  },
  { id: 'T4', amount_cr: 55, date: 'Oct 2021', status: 'DISBURSED',    milestone: '3rd floor slab complete',   milestone_met: true  },
  { id: 'T5', amount_cr: 40, date: 'PENDING',  status: 'PENDING',      milestone: '6th floor slab complete',   milestone_met: false },
  { id: 'T6', amount_cr: 30, date: 'TBD',      status: 'CONDITIONAL',  milestone: 'Possession-ready clearance', milestone_met: false },
]

export interface DivergencePoint {
  quarter: string
  pct_drawn: number
  pct_built: number
}

export const OZONE_DIVERGENCE: DivergencePoint[] = [
  { quarter: 'Q1 2021', pct_drawn: 20, pct_built: 25 },
  { quarter: 'Q2 2021', pct_drawn: 36, pct_built: 38 },
  { quarter: 'Q3 2021', pct_drawn: 50, pct_built: 43 },
  { quarter: 'Q4 2021', pct_drawn: 60, pct_built: 44 },
  { quarter: 'Q1 2022', pct_drawn: 68, pct_built: 43 },
  { quarter: 'Q2 2022', pct_drawn: 72, pct_built: 43 },
  { quarter: 'Q3 2022', pct_drawn: 72, pct_built: 43 },
  { quarter: 'Q4 2022', pct_drawn: 72, pct_built: 43 },
]

export interface CascadeProject {
  id: string
  name: string
  outstanding_cr: number
  risk_band: RiskBand
  risk_score: number
  escrow_pct: number
  escrow_concern: string
  city: string
}

// Tranche schedules for all RED projects (keyed by project ID)
export const TRANCHE_DATA: Record<string, TrancheRow[]> = {
  'ozone-urbana': OZONE_TRANCHES, // populated below — forward ref resolved at runtime
  'concord-meridian': [
    { id: 'T1', amount_cr: 35, date: 'Jan 2021', status: 'DISBURSED',    milestone: 'Foundation complete',            milestone_met: true  },
    { id: 'T2', amount_cr: 28, date: 'Apr 2021', status: 'DISBURSED',    milestone: 'Basement slab complete',          milestone_met: true  },
    { id: 'T3', amount_cr: 30, date: 'Aug 2021', status: 'DISBURSED',    milestone: 'Ground floor structure',          milestone_met: true  },
    { id: 'T4', amount_cr: 22, date: 'Dec 2021', status: 'DISBURSED',    milestone: '4th floor slab complete',         milestone_met: true  },
    { id: 'T5', amount_cr: 25, date: 'Feb 2022', status: 'DISBURSED',    milestone: 'Roof slab (6th floor) complete',  milestone_met: false },
    { id: 'T6', amount_cr:  0, date: 'STALLED',  status: 'CONDITIONAL',  milestone: 'Possession-ready (OC applied)',   milestone_met: false },
  ],
  'regent-heights': [
    { id: 'T1', amount_cr: 25, date: 'Mar 2021', status: 'DISBURSED',    milestone: 'Foundation complete',            milestone_met: true  },
    { id: 'T2', amount_cr: 20, date: 'Jul 2021', status: 'DISBURSED',    milestone: 'Plinth & basement complete',      milestone_met: true  },
    { id: 'T3', amount_cr: 22, date: 'Nov 2021', status: 'DISBURSED',    milestone: 'Ground floor structure',          milestone_met: true  },
    { id: 'T4', amount_cr: 18, date: 'Mar 2022', status: 'DISBURSED',    milestone: '3rd floor slab',                  milestone_met: true  },
    { id: 'T5', amount_cr: 10, date: 'Sep 2022', status: 'DISBURSED',    milestone: 'Roof slab — partial',             milestone_met: false },
    { id: 'T6', amount_cr:  5, date: 'PENDING',  status: 'PENDING',      milestone: 'Waterproofing & interiors done',  milestone_met: false },
  ],
}

export const OZONE_CASCADE: CascadeProject[] = [
  {
    id: 'ozone-urbana',
    name: 'Ozone Urbana',
    outstanding_cr: 180,
    risk_band: 'red',
    risk_score: 312,
    escrow_pct: 8,
    escrow_concern: 'Escrow ₹4.2 Cr on ₹52 Cr collected (8%) — 62 pp below RERA minimum of 70%',
    city: 'Bengaluru',
  },
  {
    id: 'ozone-westgate',
    name: 'Ozone Westgate',
    outstanding_cr: 180,
    risk_band: 'amber',
    risk_score: 498,
    escrow_pct: 14,
    escrow_concern: 'Anomalous Q4 2022 withdrawal — ₹8.4 Cr debited same week Urbana missed QPR deadline',
    city: 'Bengaluru',
  },
  {
    id: 'ozone-park-avenue',
    name: 'Ozone Park Avenue',
    outstanding_cr: 160,
    risk_band: 'amber',
    risk_score: 512,
    escrow_pct: 16,
    escrow_concern: 'Below 70% threshold for 3 consecutive quarters; RERA notice received Q1 2023',
    city: 'Bengaluru',
  },
]
